### ISSUE TITLE
Problem in ./start.sh exceptions.AttributeError: 'module' object has no attribute 'IPluggableAuthenticationModules'

### ISSUE THREAD

**Issue by miha237** [desaster/kippo#202]
I have an error in start.sh (I'm on Ubuntu 14.04) :

(envirt)michel@yotra:~/kippo/kippo-master$ ./start.sh
twistd (the Twisted daemon) 16.0.0
Copyright (c) 2001-2016 Twisted Matrix Laboratories.
See LICENSE for details.
Starting kippo in the background...
Unhandled Error
Traceback (most recent call last):
File "/home/michel/envirt/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-i686.egg/twisted/application/app.py", line 617, in run
runApp(config)
File "/home/michel/envirt/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-i686.egg/twisted/scripts/twistd.py", line 25, in runApp
_SomeApplicationRunner(config).run()
File "/home/michel/envirt/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-i686.egg/twisted/application/app.py", line 348, in run
self.application = self.createOrGetApplication()
File "/home/michel/envirt/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-i686.egg/twisted/application/app.py", line 413, in createOrGetApplication
application = getApplication(self.config, passphrase)
--- ---
File "/home/michel/envirt/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-i686.egg/twisted/application/app.py", line 424, in getApplication
application = service.loadApplication(filename, style, passphrase)
File "/home/michel/envirt/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-i686.egg/twisted/application/service.py", line 411, in loadApplication
passphrase)
File "/home/michel/envirt/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-i686.egg/twisted/persisted/sob.py", line 224, in loadValueFromFile
eval(codeObj, d, d)
File "kippo.tac", line 26, in
import kippo.core.auth
File "/home/michel/kippo/kippo-master/kippo/core/auth.py", line 102, in
class HoneypotPasswordChecker:
File "/home/michel/kippo/kippo-master/kippo/core/auth.py", line 105, in HoneypotPasswordChecker
credentialInterfaces = (credentials.IUsernamePassword, credentials.IPluggableAuthenticationModules)
exceptions.AttributeError: 'module' object has no attribute 'IPluggableAuthenticationModules'

Failed to load application: 'module' object has no attribute 'IPluggableAuthenticationModules'

Please help me.
Thanks

**Comment by micheloosterhof** [comment]
Your versions of Twisted and Kippo are not compatible.
(You can try http://github.com/micheloosterhof/cowrie for a honeypot that works with Twisted 16.0)

**Comment by gymzombie** [comment]
Any ideas what versions of Twisted do work with Kippo?

**Comment by desaster** [comment]
Last twisted version that kippo works with is 15.1.0.

**Comment by Wheaties466** [comment]
if the install script installs it with apt. Just `apt remove twisted -y && pip install twisted==15.1.0`
